services:

  order-service:
    image: order-service:1.0

    build:
      context: .
      dockerfile: Dockerfile

    container_name: order-service

    restart: unless-stopped

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}

      SERVER_PORT: ${SERVER_PORT}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      USER_SERVICE_DOCKER_URL: ${USER_SERVICE_DOCKER_URL}

      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - order-service-network
      - user-service-network
      - kafka-network


  postgres:
    image: postgres:17

    container_name: order-service-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST_PORT: ${POSTGRES_HOST_PORT}

    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"

    command: -p ${POSTGRES_PORT}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -p ${POSTGRES_PORT}" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - order-service-network


volumes:
  postgres-data:


networks:
  order-service-network:
    driver: bridge
    name: order-service-network
  user-service-network:
    external: true
    name: user-service-network
  kafka-network:
    external: true
    name: kafka-network