services:

  order-service:
    image: order-service:1.0

    build:
      context: .
      dockerfile: Dockerfile

    container_name: order-service

    restart: unless-stopped

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}

      SERVER_PORT: ${SERVER_PORT}

      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DRIVER: ${POSTGRES_DRIVER}

      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}

      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}

      GATEWAY_API_KEY: ${GATEWAY_API_KEY}

      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

    networks:
      - order-service-network
      - user-service-network
      - kafka-network


  postgres:
    image: postgres:17

    container_name: order-service-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_HOST_PORT: ${POSTGRES_HOST_PORT}

    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"

    command: -p ${POSTGRES_PORT}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -p ${POSTGRES_PORT}" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - order-service-network


  kafka:
    image: apache/kafka:4.3.1

    container_name: order-service-kafka

    restart: unless-stopped

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${KAFKA_HOST}:${KAFKA_PORT},EXTERNAL://localhost:${KAFKA_HOST_PORT}
      KAFKA_LISTENERS: CONTROLLER://${KAFKA_HOST}:${KAFKA_CONTROLLER_PORT},INTERNAL://${KAFKA_HOST}:${KAFKA_PORT},EXTERNAL://0.0.0.0:${KAFKA_HOST_PORT}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${KAFKA_HOST}:${KAFKA_CONTROLLER_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    ports:
      - "${KAFKA_HOST_PORT}:${KAFKA_HOST_PORT}"

    healthcheck:
      test: [ "CMD-SHELL", "ps aux | grep -v grep | grep kafka || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

    volumes:
      - kafka-data:/var/lib/kafka/data

    networks:
      - kafka-network

volumes:
  postgres-data:
  kafka-data:

networks:
  order-service-network:
    driver: bridge
    name: order-service-network
  user-service-network:
    external: true
    name: user-service-network
  kafka-network:
    driver: bridge
    name: kafka-network