spring.application.name=order-service
spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_EXPIRATION}

spring.profiles.active=${ACTIVE_PROFILE}