server.port=${SERVER_PORT}

user-service.url=${USER_SERVICE_DOCKER_URL}

spring.datasource.url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.alphanumeric-ids.enabled=true

resilience4j.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.user-service.register-health-indicator=true
resilience4j.circuitbreaker.instances.user-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.user-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.user-service.wait-duration-in-open-state=5s